--1. How to get the sense of data?

SELECT * FROM [dbo].[vehicle];
SELECT * FROM [dbo].[accident];

--The following questions have been generated by ChatGPT

--Analyzing Vehicle Dataset Separately

--1. What types of vehicles are present in the dataset?

SELECT DISTINCT VehicleType FROM [dbo].[vehicle];

--2. How many unique vehicles are there in total?

SELECT COUNT(DISTINCT VehicleType) AS UniqueVehiclesCount FROM [dbo].[vehicle];

--3. How many vehicles are there in total?

SELECT COUNT(*) AS TotalVehiclesCount FROM [dbo].[vehicle];

--4. Can you list the unique journey purposes mentioned in the dataset?

SELECT DISTINCT JourneyPurpose FROM [dbo].[vehicle];

--5. What are the different types of vehicles in the dataset, and how many occurrences are there for each type?

SELECT VehicleType, COUNT(*) AS Occurrences
FROM [dbo].[vehicle]
GROUP BY VehicleType;

--6. Can you provide the distribution of vehicles based on their propulsion type (e.g., petrol, diesel, electric)?

SELECT Propulsion, COUNT(*) AS Occurrences
FROM [dbo].[vehicle]
GROUP BY Propulsion;

-- Changing the data type in AgeVehicle; it is currently nvarchar(200), so we cannot find the avg age of vehicles with this data type

ALTER TABLE [dbo].[vehicle] ALTER COLUMN [AgeVehicle] INT;

--7. What is the average age of vehicles involved in accidents?

SELECT AVG(CAST(AgeVehicle AS FLOAT)) AS AverageAgeOfVehicles FROM [dbo].[vehicle];

--8. How many accidents involve vehicles with the steering wheel on the left-hand side?

SELECT COUNT(*) AS AccidentWithLeftHandSteering
FROM [dbo].[vehicle]
WHERE [LeftHand] = 'Yes';

--9. What is the most common journey purpose for vehicles involved in accidents?

SELECT JourneyPurpose, COUNT(*) AS Occurrences
FROM [dbo].[vehicle]
GROUP BY JourneyPurpose
ORDER BY Occurrences DESC
LIMIT 1;

--Analyzing Accident Dataset Separately

--1. What is the distribution of accident severity levels in the dataset?

select [Severity], count(*) as DistAccidentSeverity from [dbo].[accident]
group by [Severity]

--2. Can you provide insights into the number of accidents that occurred on each day of the week?

select [Day], count(*) as ByDay from [dbo].[accident] group by [Day] order by ByDay desc

--3. What is the average speed limit in accidents with different severity levels?

select [Severity], avg(SpeedLimit) as AvgSpeedLimit from [dbo].[accident] group by [Severity]

--4. How do light conditions correlate with the severity of accidents?

SELECT LightConditions, Severity, COUNT(*) AS AccidentCount
FROM [dbo].[accident]
GROUP BY LightConditions, Severity
ORDER BY LightConditions, Severity;

--5. What are the most common weather and road conditions during accidents?

SELECT WeatherConditions, RoadConditions, COUNT(*) AS AccidentCount
FROM [dbo].[accident]
GROUP BY WeatherConditions, RoadConditions
ORDER BY AccidentCount DESC;

--6. How many accidents are recorded in the dataset?

select count(*) as AccidentCount from [dbo].[accident]

--7. Can you identify the unique areas mentioned in the dataset?

select distinct[Area], count(*) as Counts from [dbo].[accident] group by [Area]

--Combined Analysis of both the tables([dbo].[accident] and [dbo].[vehicle])

--1. Is there a correlation between the age of the vehicle and the severity of the accidents it is involved in?

SELECT a.Severity, AVG(v.AgeVehicle) as AverageAge
FROM [dbo].[Accident] a
INNER JOIN [dbo].[Vehicle] v ON a.AccidentIndex = v.AccidentIndex
GROUP BY a.Severity;

--2. How does the journey purpose of a vehicle relate to the severity of the accidents it is involved in?

SELECT v.[JourneyPurpose], a.[Severity]
FROM [dbo].[Accident] a
INNER JOIN [dbo].[Vehicle] v ON a.AccidentIndex = v.AccidentIndex
GROUP BY v.[JourneyPurpose], a.[Severity];